// Code generated by entc, DO NOT EDIT.

package subdistrict

const (
	// Label holds the string label denoting the subdistrict type in the database.
	Label = "subdistrict"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSubdistrict holds the string denoting the subdistrict field in the database.
	FieldSubdistrict = "subdistrict"

	// EdgeProvince holds the string denoting the province edge name in mutations.
	EdgeProvince = "province"

	// Table holds the table name of the subdistrict in the database.
	Table = "subdistricts"
	// ProvinceTable is the table the holds the province relation/edge.
	ProvinceTable = "provinces"
	// ProvinceInverseTable is the table name for the Province entity.
	// It exists in this package in order to avoid circular dependency with the "province" package.
	ProvinceInverseTable = "provinces"
	// ProvinceColumn is the table column denoting the province relation/edge.
	ProvinceColumn = "subdistrict"
)

// Columns holds all SQL columns for subdistrict fields.
var Columns = []string{
	FieldID,
	FieldSubdistrict,
}

var (
	// SubdistrictValidator is a validator for the "subdistrict" field. It is called by the builders before save.
	SubdistrictValidator func(string) error
)
