// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// District is the predicate function for district builders.
type District func(*sql.Selector)

// Province is the predicate function for province builders.
type Province func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)

// Subdistrict is the predicate function for subdistrict builders.
type Subdistrict func(*sql.Selector)
