// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/oreo/app/ent/district"
	"github.com/oreo/app/ent/province"
	"github.com/oreo/app/ent/student"
	"github.com/oreo/app/ent/subdistrict"
)

// ProvinceCreate is the builder for creating a Province entity.
type ProvinceCreate struct {
	config
	mutation *ProvinceMutation
	hooks    []Hook
}

// SetName sets the name field.
func (pc *ProvinceCreate) SetName(s string) *ProvinceCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetDistrictID sets the district edge to District by id.
func (pc *ProvinceCreate) SetDistrictID(id int) *ProvinceCreate {
	pc.mutation.SetDistrictID(id)
	return pc
}

// SetNillableDistrictID sets the district edge to District by id if the given value is not nil.
func (pc *ProvinceCreate) SetNillableDistrictID(id *int) *ProvinceCreate {
	if id != nil {
		pc = pc.SetDistrictID(*id)
	}
	return pc
}

// SetDistrict sets the district edge to District.
func (pc *ProvinceCreate) SetDistrict(d *District) *ProvinceCreate {
	return pc.SetDistrictID(d.ID)
}

// SetSubdistrictID sets the subdistrict edge to Subdistrict by id.
func (pc *ProvinceCreate) SetSubdistrictID(id int) *ProvinceCreate {
	pc.mutation.SetSubdistrictID(id)
	return pc
}

// SetNillableSubdistrictID sets the subdistrict edge to Subdistrict by id if the given value is not nil.
func (pc *ProvinceCreate) SetNillableSubdistrictID(id *int) *ProvinceCreate {
	if id != nil {
		pc = pc.SetSubdistrictID(*id)
	}
	return pc
}

// SetSubdistrict sets the subdistrict edge to Subdistrict.
func (pc *ProvinceCreate) SetSubdistrict(s *Subdistrict) *ProvinceCreate {
	return pc.SetSubdistrictID(s.ID)
}

// SetStudentID sets the student edge to Student by id.
func (pc *ProvinceCreate) SetStudentID(id int) *ProvinceCreate {
	pc.mutation.SetStudentID(id)
	return pc
}

// SetNillableStudentID sets the student edge to Student by id if the given value is not nil.
func (pc *ProvinceCreate) SetNillableStudentID(id *int) *ProvinceCreate {
	if id != nil {
		pc = pc.SetStudentID(*id)
	}
	return pc
}

// SetStudent sets the student edge to Student.
func (pc *ProvinceCreate) SetStudent(s *Student) *ProvinceCreate {
	return pc.SetStudentID(s.ID)
}

// Mutation returns the ProvinceMutation object of the builder.
func (pc *ProvinceCreate) Mutation() *ProvinceMutation {
	return pc.mutation
}

// Save creates the Province in the database.
func (pc *ProvinceCreate) Save(ctx context.Context) (*Province, error) {
	if _, ok := pc.mutation.Name(); !ok {
		return nil, &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := province.NameValidator(v); err != nil {
			return nil, &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	var (
		err  error
		node *Province
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProvinceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProvinceCreate) SaveX(ctx context.Context) *Province {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *ProvinceCreate) sqlSave(ctx context.Context) (*Province, error) {
	pr, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pr.ID = int(id)
	return pr, nil
}

func (pc *ProvinceCreate) createSpec() (*Province, *sqlgraph.CreateSpec) {
	var (
		pr    = &Province{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: province.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: province.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: province.FieldName,
		})
		pr.Name = value
	}
	if nodes := pc.mutation.DistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.DistrictTable,
			Columns: []string{province.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: district.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.SubdistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.SubdistrictTable,
			Columns: []string{province.SubdistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: subdistrict.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.StudentTable,
			Columns: []string{province.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: student.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pr, _spec
}
