// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/oreo/app/ent/district"
	"github.com/oreo/app/ent/predicate"
	"github.com/oreo/app/ent/province"
	"github.com/oreo/app/ent/student"
	"github.com/oreo/app/ent/subdistrict"
)

// ProvinceUpdate is the builder for updating Province entities.
type ProvinceUpdate struct {
	config
	hooks      []Hook
	mutation   *ProvinceMutation
	predicates []predicate.Province
}

// Where adds a new predicate for the builder.
func (pu *ProvinceUpdate) Where(ps ...predicate.Province) *ProvinceUpdate {
	pu.predicates = append(pu.predicates, ps...)
	return pu
}

// SetName sets the name field.
func (pu *ProvinceUpdate) SetName(s string) *ProvinceUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetDistrictID sets the district edge to District by id.
func (pu *ProvinceUpdate) SetDistrictID(id int) *ProvinceUpdate {
	pu.mutation.SetDistrictID(id)
	return pu
}

// SetNillableDistrictID sets the district edge to District by id if the given value is not nil.
func (pu *ProvinceUpdate) SetNillableDistrictID(id *int) *ProvinceUpdate {
	if id != nil {
		pu = pu.SetDistrictID(*id)
	}
	return pu
}

// SetDistrict sets the district edge to District.
func (pu *ProvinceUpdate) SetDistrict(d *District) *ProvinceUpdate {
	return pu.SetDistrictID(d.ID)
}

// SetSubdistrictID sets the subdistrict edge to Subdistrict by id.
func (pu *ProvinceUpdate) SetSubdistrictID(id int) *ProvinceUpdate {
	pu.mutation.SetSubdistrictID(id)
	return pu
}

// SetNillableSubdistrictID sets the subdistrict edge to Subdistrict by id if the given value is not nil.
func (pu *ProvinceUpdate) SetNillableSubdistrictID(id *int) *ProvinceUpdate {
	if id != nil {
		pu = pu.SetSubdistrictID(*id)
	}
	return pu
}

// SetSubdistrict sets the subdistrict edge to Subdistrict.
func (pu *ProvinceUpdate) SetSubdistrict(s *Subdistrict) *ProvinceUpdate {
	return pu.SetSubdistrictID(s.ID)
}

// SetStudentID sets the student edge to Student by id.
func (pu *ProvinceUpdate) SetStudentID(id int) *ProvinceUpdate {
	pu.mutation.SetStudentID(id)
	return pu
}

// SetNillableStudentID sets the student edge to Student by id if the given value is not nil.
func (pu *ProvinceUpdate) SetNillableStudentID(id *int) *ProvinceUpdate {
	if id != nil {
		pu = pu.SetStudentID(*id)
	}
	return pu
}

// SetStudent sets the student edge to Student.
func (pu *ProvinceUpdate) SetStudent(s *Student) *ProvinceUpdate {
	return pu.SetStudentID(s.ID)
}

// Mutation returns the ProvinceMutation object of the builder.
func (pu *ProvinceUpdate) Mutation() *ProvinceMutation {
	return pu.mutation
}

// ClearDistrict clears the district edge to District.
func (pu *ProvinceUpdate) ClearDistrict() *ProvinceUpdate {
	pu.mutation.ClearDistrict()
	return pu
}

// ClearSubdistrict clears the subdistrict edge to Subdistrict.
func (pu *ProvinceUpdate) ClearSubdistrict() *ProvinceUpdate {
	pu.mutation.ClearSubdistrict()
	return pu
}

// ClearStudent clears the student edge to Student.
func (pu *ProvinceUpdate) ClearStudent() *ProvinceUpdate {
	pu.mutation.ClearStudent()
	return pu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (pu *ProvinceUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := pu.mutation.Name(); ok {
		if err := province.NameValidator(v); err != nil {
			return 0, &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProvinceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProvinceUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProvinceUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProvinceUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *ProvinceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   province.Table,
			Columns: province.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: province.FieldID,
			},
		},
	}
	if ps := pu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: province.FieldName,
		})
	}
	if pu.mutation.DistrictCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.DistrictTable,
			Columns: []string{province.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: district.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.DistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.DistrictTable,
			Columns: []string{province.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: district.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.SubdistrictCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.SubdistrictTable,
			Columns: []string{province.SubdistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: subdistrict.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.SubdistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.SubdistrictTable,
			Columns: []string{province.SubdistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: subdistrict.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.StudentTable,
			Columns: []string{province.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: student.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.StudentTable,
			Columns: []string{province.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: student.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{province.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ProvinceUpdateOne is the builder for updating a single Province entity.
type ProvinceUpdateOne struct {
	config
	hooks    []Hook
	mutation *ProvinceMutation
}

// SetName sets the name field.
func (puo *ProvinceUpdateOne) SetName(s string) *ProvinceUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetDistrictID sets the district edge to District by id.
func (puo *ProvinceUpdateOne) SetDistrictID(id int) *ProvinceUpdateOne {
	puo.mutation.SetDistrictID(id)
	return puo
}

// SetNillableDistrictID sets the district edge to District by id if the given value is not nil.
func (puo *ProvinceUpdateOne) SetNillableDistrictID(id *int) *ProvinceUpdateOne {
	if id != nil {
		puo = puo.SetDistrictID(*id)
	}
	return puo
}

// SetDistrict sets the district edge to District.
func (puo *ProvinceUpdateOne) SetDistrict(d *District) *ProvinceUpdateOne {
	return puo.SetDistrictID(d.ID)
}

// SetSubdistrictID sets the subdistrict edge to Subdistrict by id.
func (puo *ProvinceUpdateOne) SetSubdistrictID(id int) *ProvinceUpdateOne {
	puo.mutation.SetSubdistrictID(id)
	return puo
}

// SetNillableSubdistrictID sets the subdistrict edge to Subdistrict by id if the given value is not nil.
func (puo *ProvinceUpdateOne) SetNillableSubdistrictID(id *int) *ProvinceUpdateOne {
	if id != nil {
		puo = puo.SetSubdistrictID(*id)
	}
	return puo
}

// SetSubdistrict sets the subdistrict edge to Subdistrict.
func (puo *ProvinceUpdateOne) SetSubdistrict(s *Subdistrict) *ProvinceUpdateOne {
	return puo.SetSubdistrictID(s.ID)
}

// SetStudentID sets the student edge to Student by id.
func (puo *ProvinceUpdateOne) SetStudentID(id int) *ProvinceUpdateOne {
	puo.mutation.SetStudentID(id)
	return puo
}

// SetNillableStudentID sets the student edge to Student by id if the given value is not nil.
func (puo *ProvinceUpdateOne) SetNillableStudentID(id *int) *ProvinceUpdateOne {
	if id != nil {
		puo = puo.SetStudentID(*id)
	}
	return puo
}

// SetStudent sets the student edge to Student.
func (puo *ProvinceUpdateOne) SetStudent(s *Student) *ProvinceUpdateOne {
	return puo.SetStudentID(s.ID)
}

// Mutation returns the ProvinceMutation object of the builder.
func (puo *ProvinceUpdateOne) Mutation() *ProvinceMutation {
	return puo.mutation
}

// ClearDistrict clears the district edge to District.
func (puo *ProvinceUpdateOne) ClearDistrict() *ProvinceUpdateOne {
	puo.mutation.ClearDistrict()
	return puo
}

// ClearSubdistrict clears the subdistrict edge to Subdistrict.
func (puo *ProvinceUpdateOne) ClearSubdistrict() *ProvinceUpdateOne {
	puo.mutation.ClearSubdistrict()
	return puo
}

// ClearStudent clears the student edge to Student.
func (puo *ProvinceUpdateOne) ClearStudent() *ProvinceUpdateOne {
	puo.mutation.ClearStudent()
	return puo
}

// Save executes the query and returns the updated entity.
func (puo *ProvinceUpdateOne) Save(ctx context.Context) (*Province, error) {
	if v, ok := puo.mutation.Name(); ok {
		if err := province.NameValidator(v); err != nil {
			return nil, &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}

	var (
		err  error
		node *Province
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProvinceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProvinceUpdateOne) SaveX(ctx context.Context) *Province {
	pr, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return pr
}

// Exec executes the query on the entity.
func (puo *ProvinceUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProvinceUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *ProvinceUpdateOne) sqlSave(ctx context.Context) (pr *Province, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   province.Table,
			Columns: province.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: province.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Province.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := puo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: province.FieldName,
		})
	}
	if puo.mutation.DistrictCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.DistrictTable,
			Columns: []string{province.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: district.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.DistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.DistrictTable,
			Columns: []string{province.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: district.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.SubdistrictCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.SubdistrictTable,
			Columns: []string{province.SubdistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: subdistrict.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.SubdistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.SubdistrictTable,
			Columns: []string{province.SubdistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: subdistrict.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.StudentTable,
			Columns: []string{province.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: student.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.StudentTable,
			Columns: []string{province.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: student.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	pr = &Province{config: puo.config}
	_spec.Assign = pr.assignValues
	_spec.ScanValues = pr.scanValues()
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{province.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return pr, nil
}
