// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/oreo/app/ent/district"
	"github.com/oreo/app/ent/province"
	"github.com/oreo/app/ent/schema"
	"github.com/oreo/app/ent/student"
	"github.com/oreo/app/ent/subdistrict"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	districtFields := schema.District{}.Fields()
	_ = districtFields
	// districtDescDistrict is the schema descriptor for district field.
	districtDescDistrict := districtFields[0].Descriptor()
	// district.DistrictValidator is a validator for the "district" field. It is called by the builders before save.
	district.DistrictValidator = districtDescDistrict.Validators[0].(func(string) error)
	provinceFields := schema.Province{}.Fields()
	_ = provinceFields
	// provinceDescName is the schema descriptor for name field.
	provinceDescName := provinceFields[0].Descriptor()
	// province.NameValidator is a validator for the "name" field. It is called by the builders before save.
	province.NameValidator = provinceDescName.Validators[0].(func(string) error)
	studentFields := schema.Student{}.Fields()
	_ = studentFields
	// studentDescStudent is the schema descriptor for student field.
	studentDescStudent := studentFields[0].Descriptor()
	// student.StudentValidator is a validator for the "student" field. It is called by the builders before save.
	student.StudentValidator = studentDescStudent.Validators[0].(func(string) error)
	subdistrictFields := schema.Subdistrict{}.Fields()
	_ = subdistrictFields
	// subdistrictDescSubdistrict is the schema descriptor for subdistrict field.
	subdistrictDescSubdistrict := subdistrictFields[0].Descriptor()
	// subdistrict.SubdistrictValidator is a validator for the "subdistrict" field. It is called by the builders before save.
	subdistrict.SubdistrictValidator = subdistrictDescSubdistrict.Validators[0].(func(string) error)
}
