// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/oreo/app/ent/province"
	"github.com/oreo/app/ent/subdistrict"
)

// SubdistrictCreate is the builder for creating a Subdistrict entity.
type SubdistrictCreate struct {
	config
	mutation *SubdistrictMutation
	hooks    []Hook
}

// SetSubdistrict sets the subdistrict field.
func (sc *SubdistrictCreate) SetSubdistrict(s string) *SubdistrictCreate {
	sc.mutation.SetSubdistrict(s)
	return sc
}

// AddProvinceIDs adds the province edge to Province by ids.
func (sc *SubdistrictCreate) AddProvinceIDs(ids ...int) *SubdistrictCreate {
	sc.mutation.AddProvinceIDs(ids...)
	return sc
}

// AddProvince adds the province edges to Province.
func (sc *SubdistrictCreate) AddProvince(p ...*Province) *SubdistrictCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return sc.AddProvinceIDs(ids...)
}

// Mutation returns the SubdistrictMutation object of the builder.
func (sc *SubdistrictCreate) Mutation() *SubdistrictMutation {
	return sc.mutation
}

// Save creates the Subdistrict in the database.
func (sc *SubdistrictCreate) Save(ctx context.Context) (*Subdistrict, error) {
	if _, ok := sc.mutation.Subdistrict(); !ok {
		return nil, &ValidationError{Name: "subdistrict", err: errors.New("ent: missing required field \"subdistrict\"")}
	}
	if v, ok := sc.mutation.Subdistrict(); ok {
		if err := subdistrict.SubdistrictValidator(v); err != nil {
			return nil, &ValidationError{Name: "subdistrict", err: fmt.Errorf("ent: validator failed for field \"subdistrict\": %w", err)}
		}
	}
	var (
		err  error
		node *Subdistrict
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SubdistrictMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SubdistrictCreate) SaveX(ctx context.Context) *Subdistrict {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *SubdistrictCreate) sqlSave(ctx context.Context) (*Subdistrict, error) {
	s, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sc *SubdistrictCreate) createSpec() (*Subdistrict, *sqlgraph.CreateSpec) {
	var (
		s     = &Subdistrict{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: subdistrict.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: subdistrict.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.Subdistrict(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: subdistrict.FieldSubdistrict,
		})
		s.Subdistrict = value
	}
	if nodes := sc.mutation.ProvinceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subdistrict.ProvinceTable,
			Columns: []string{subdistrict.ProvinceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: province.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return s, _spec
}
