// Code generated by entc, DO NOT EDIT.

package student

const (
	// Label holds the string label denoting the student type in the database.
	Label = "student"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStudent holds the string denoting the student field in the database.
	FieldStudent = "student"

	// EdgeProvince holds the string denoting the province edge name in mutations.
	EdgeProvince = "province"

	// Table holds the table name of the student in the database.
	Table = "students"
	// ProvinceTable is the table the holds the province relation/edge.
	ProvinceTable = "provinces"
	// ProvinceInverseTable is the table name for the Province entity.
	// It exists in this package in order to avoid circular dependency with the "province" package.
	ProvinceInverseTable = "provinces"
	// ProvinceColumn is the table column denoting the province relation/edge.
	ProvinceColumn = "student"
)

// Columns holds all SQL columns for student fields.
var Columns = []string{
	FieldID,
	FieldStudent,
}

var (
	// StudentValidator is a validator for the "student" field. It is called by the builders before save.
	StudentValidator func(string) error
)
