// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// DistrictsColumns holds the columns for the "districts" table.
	DistrictsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "district", Type: field.TypeString},
	}
	// DistrictsTable holds the schema information for the "districts" table.
	DistrictsTable = &schema.Table{
		Name:        "districts",
		Columns:     DistrictsColumns,
		PrimaryKey:  []*schema.Column{DistrictsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ProvincesColumns holds the columns for the "provinces" table.
	ProvincesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "district", Type: field.TypeInt, Nullable: true},
		{Name: "student", Type: field.TypeInt, Nullable: true},
		{Name: "subdistrict", Type: field.TypeInt, Nullable: true},
	}
	// ProvincesTable holds the schema information for the "provinces" table.
	ProvincesTable = &schema.Table{
		Name:       "provinces",
		Columns:    ProvincesColumns,
		PrimaryKey: []*schema.Column{ProvincesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "provinces_districts_province",
				Columns: []*schema.Column{ProvincesColumns[2]},

				RefColumns: []*schema.Column{DistrictsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "provinces_students_province",
				Columns: []*schema.Column{ProvincesColumns[3]},

				RefColumns: []*schema.Column{StudentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "provinces_subdistricts_province",
				Columns: []*schema.Column{ProvincesColumns[4]},

				RefColumns: []*schema.Column{SubdistrictsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// StudentsColumns holds the columns for the "students" table.
	StudentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "student", Type: field.TypeString},
	}
	// StudentsTable holds the schema information for the "students" table.
	StudentsTable = &schema.Table{
		Name:        "students",
		Columns:     StudentsColumns,
		PrimaryKey:  []*schema.Column{StudentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// SubdistrictsColumns holds the columns for the "subdistricts" table.
	SubdistrictsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "subdistrict", Type: field.TypeString},
	}
	// SubdistrictsTable holds the schema information for the "subdistricts" table.
	SubdistrictsTable = &schema.Table{
		Name:        "subdistricts",
		Columns:     SubdistrictsColumns,
		PrimaryKey:  []*schema.Column{SubdistrictsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DistrictsTable,
		ProvincesTable,
		StudentsTable,
		SubdistrictsTable,
	}
)

func init() {
	ProvincesTable.ForeignKeys[0].RefTable = DistrictsTable
	ProvincesTable.ForeignKeys[1].RefTable = StudentsTable
	ProvincesTable.ForeignKeys[2].RefTable = SubdistrictsTable
}
