// Code generated by entc, DO NOT EDIT.

package province

const (
	// Label holds the string label denoting the province type in the database.
	Label = "province"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeDistrict holds the string denoting the district edge name in mutations.
	EdgeDistrict = "district"
	// EdgeSubdistrict holds the string denoting the subdistrict edge name in mutations.
	EdgeSubdistrict = "subdistrict"
	// EdgeStudent holds the string denoting the student edge name in mutations.
	EdgeStudent = "student"

	// Table holds the table name of the province in the database.
	Table = "provinces"
	// DistrictTable is the table the holds the district relation/edge.
	DistrictTable = "provinces"
	// DistrictInverseTable is the table name for the District entity.
	// It exists in this package in order to avoid circular dependency with the "district" package.
	DistrictInverseTable = "districts"
	// DistrictColumn is the table column denoting the district relation/edge.
	DistrictColumn = "district"
	// SubdistrictTable is the table the holds the subdistrict relation/edge.
	SubdistrictTable = "provinces"
	// SubdistrictInverseTable is the table name for the Subdistrict entity.
	// It exists in this package in order to avoid circular dependency with the "subdistrict" package.
	SubdistrictInverseTable = "subdistricts"
	// SubdistrictColumn is the table column denoting the subdistrict relation/edge.
	SubdistrictColumn = "subdistrict"
	// StudentTable is the table the holds the student relation/edge.
	StudentTable = "provinces"
	// StudentInverseTable is the table name for the Student entity.
	// It exists in this package in order to avoid circular dependency with the "student" package.
	StudentInverseTable = "students"
	// StudentColumn is the table column denoting the student relation/edge.
	StudentColumn = "student"
)

// Columns holds all SQL columns for province fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Province type.
var ForeignKeys = []string{
	"district",
	"student",
	"subdistrict",
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
