/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersProvince
 */
export interface ControllersProvince {
    /**
     * 
     * @type {number}
     * @memberof ControllersProvince
     */
    district?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersProvince
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersProvince
     */
    student?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersProvince
     */
    subdistrict?: number;
}

export function ControllersProvinceFromJSON(json: any): ControllersProvince {
    return ControllersProvinceFromJSONTyped(json, false);
}

export function ControllersProvinceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersProvince {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'district': !exists(json, 'district') ? undefined : json['district'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'student': !exists(json, 'student') ? undefined : json['student'],
        'subdistrict': !exists(json, 'subdistrict') ? undefined : json['subdistrict'],
    };
}

export function ControllersProvinceToJSON(value?: ControllersProvince | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'district': value.district,
        'name': value.name,
        'student': value.student,
        'subdistrict': value.subdistrict,
    };
}


