/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntStudentEdges,
    EntStudentEdgesFromJSON,
    EntStudentEdgesFromJSONTyped,
    EntStudentEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntStudent
 */
export interface EntStudent {
    /**
     * 
     * @type {EntStudentEdges}
     * @memberof EntStudent
     */
    edges?: EntStudentEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntStudent
     */
    id?: number;
    /**
     * Student holds the value of the "student" field.
     * @type {string}
     * @memberof EntStudent
     */
    student?: string;
}

export function EntStudentFromJSON(json: any): EntStudent {
    return EntStudentFromJSONTyped(json, false);
}

export function EntStudentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntStudent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntStudentEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'student': !exists(json, 'student') ? undefined : json['student'],
    };
}

export function EntStudentToJSON(value?: EntStudent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntStudentEdgesToJSON(value.edges),
        'id': value.id,
        'student': value.student,
    };
}


