/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntProvince,
    EntProvinceFromJSON,
    EntProvinceFromJSONTyped,
    EntProvinceToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntStudentEdges
 */
export interface EntStudentEdges {
    /**
     * Province holds the value of the province edge.
     * @type {Array<EntProvince>}
     * @memberof EntStudentEdges
     */
    province?: Array<EntProvince>;
}

export function EntStudentEdgesFromJSON(json: any): EntStudentEdges {
    return EntStudentEdgesFromJSONTyped(json, false);
}

export function EntStudentEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntStudentEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'province': !exists(json, 'province') ? undefined : ((json['province'] as Array<any>).map(EntProvinceFromJSON)),
    };
}

export function EntStudentEdgesToJSON(value?: EntStudentEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'province': value.province === undefined ? undefined : ((value.province as Array<any>).map(EntProvinceToJSON)),
    };
}


